// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Usa process.env diretamente — funciona tanto com .env (via dotenv)
  // quanto com variáveis de ambiente injetadas pelo Docker/CI
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
